workflow:
  name: "configuration-folder-structure"
  title: "Configuration - Folder Structure"
  description: "Configuration - Folder Structure"
  outputs:
    workflow-status: "'executed'"
  tasks:

    # documents-structure
    - type: "document"
      name: "install-documents"
      description: "Install documents."
      config:
        action: "update"
        embed-vector: false
        force-update: true
      documents:
        site-structure: |
          [
            {
              "title": "Moderator Website",
              "url": "https://vipplayinc-tennessee-college-football-moderator.org.machina.gg",
              "icon": "globe"
            }
          ]
        doc-structure: |
          [
            {
              "title": "Catalogue",
              "isActive": True,
              "icon": "folder",
              "items": [
                {
                  "name": "games",
                  "title": "Games",
                  "description": "The games available in the Sportradar API.",
                  "category": "Catalogue",
                  "metadata": {
                    "name": ["soccer-game"]
                  },
                  "sorters": ['_id', -1],
                  "view": "list"
                },
                {
                  "name": "teams",
                  "title": "Teams",
                  "description": "The teams available in the Sportradar API.",
                  "category": "Catalogue",
                  "metadata": {
                    "name": ["soccer-team"]
                  },
                  "sorters": ['_id', -1],
                  "view": "list"
                }
              ]
            },
            {
              "title": "Conversation",
              "isActive": True,
              "icon": "folder",
              "items": [
                {
                  "name": "threads",
                  "title": "Threads",
                  "description": "The threads available in the Conversation API.",
                  "category": "Conversation",
                  "metadata": {
                    "name": ["thread"]
                  },
                  "sorters": ['_id', -1],
                  "view": "list"
                }
              ]
            },
            {
              "title": "Editorial",
              "isActive": True,
              "icon": "folder",
              "items": [
                {
                  "name": "articles",
                  "title": "Articles",
                  "description": "The articles generated by the AI Reporter.",
                  "category": "Editorial",
                  "metadata": {
                    "name": ["content-article"]
                  },
                  "sorters": ['_id', -1],
                  "view": "list"
                },
                {
                  "name": "agenda",
                  "title": "Agenda",
                  "description": "The agenda generated by the AI Reporter.",
                  "category": "Editorial",
                  "metadata": {
                    "name": ["content-agenda"]
                  },
                  "sorters": ['_id', -1],
                  "view": "list"
                },
                {
                  "name": "images",
                  "title": "Images",
                  "description": "The images generated by the AI Reporter.",
                  "category": "Editorial",
                  "metadata": {
                    "name": ["content-image"]
                  },
                  "sorters": ['_id', -1],
                  "view": "list"
                },
                {
                  "name": "polls",
                  "title": "Polls",
                  "description": "The polls generated by the AI Reporter.",
                  "category": "Editorial",
                  "metadata": {
                    "name": ["content-poll"]
                  },
                  "sorters": ['_id', -1],
                  "view": "list"
                },
                {
                  "name": "quizzes",
                  "title": "Quizzes",
                  "description": "The quizzes generated by the AI Reporter.",
                  "category": "Editorial",
                  "metadata": {
                    "name": ["content-quiz"]
                  },
                  "sorters": ['_id', -1],
                  "view": "list"
                },
                {
                  "name": "scripts",
                  "title": "Scripts",
                  "description": "The scripts generated by the AI Reporter.",
                  "category": "Editorial",
                  "metadata": {
                    "name": ["content-script"]
                  },
                  "sorters": ['_id', -1],
                  "view": "list"
                }
              ]
            },
            {
              "title": "Knowledge",
              "isActive": True,
              "icon": "folder",
              "items": [
                {
                  "name": "snippets",
                  "title": "Snippets",
                  "description": "The snippets generated by the AI Reporter.",
                  "category": "Knowledge",
                  "metadata": {
                    "name": ["content-snippet"]
                  },
                  "sorters": ['_id', -1],
                  "view": "list"
                }
              ]
            },
            {
              "title": "Research",
              "isActive": True,
              "icon": "folder",
              "items": [
                {
                  "name": "web-images",
                  "title": "Images",
                  "description": "The web images available in the configuration.",
                  "category": "Research",
                  "metadata": {
                    "name": ["web-image"]
                  },
                  "sorters": ['_id', -1],
                  "view": "list"
                },
                {
                  "name": "web-search",
                  "title": "Searches",
                  "description": "The web searches available in the configuration.",
                  "category": "Research",
                  "metadata": {
                    "name": ["web-search"]
                  },
                  "sorters": ['_id', -1],
                  "view": "list"
                },
                {
                  "name": "web-scraping",
                  "title": "Scrapings",
                  "description": "The web scrapings generated by the AI Reporter.",
                  "category": "Research",
                  "metadata": {
                    "name": ["web-scraping"]
                  },
                  "sorters": ['_id', -1],
                  "view": "list"
                },
                {
                  "name": "video-transcript",
                  "title": "Transcripts",
                  "description": "The video transcripts generated by the AI Reporter.",
                  "category": "Research",
                  "metadata": {
                    "name": ["video-transcript"]
                  },
                  "sorters": ['_id', -1],
                  "view": "list"
                },
                {
                  "name": "videos",
                  "title": "Videos",
                  "description": "The videos available in the configuration.",
                  "category": "Research",
                  "metadata": {
                    "name": ["video-youtube"]
                  },
                  "sorters": ['_id', -1],
                  "view": "list"
                }
              ]
            }
          ]
